# Generated by Django 6.0.2 on 2026-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('total_population', models.FloatField(verbose_name='Численность населения')),
                ('urban_population', models.FloatField(verbose_name='Городское население')),
                ('rural_population', models.FloatField(verbose_name='Сельское население')),
                ('urban_percentage', models.FloatField(verbose_name='Процент городского населения')),
                ('rural_percentage', models.FloatField(verbose_name='Процент сельского населения')),
            ],
            options={
                'verbose_name': 'Численность населения',
                'verbose_name_plural': 'Численность населения',
            },
        ),
    ]
