# Generated by Django 6.0.2 on 2026-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRussia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
                ('labor_force', models.FloatField(verbose_name='Рабочая сила')),
                ('employ_people', models.FloatField(verbose_name='Занятые')),
                ('unemployed_people', models.FloatField(verbose_name='Безработные')),
                ('percent_in_labor', models.FloatField(verbose_name='Уровень участия в составе рабочей силы, в %')),
                ('percent_employed', models.FloatField(verbose_name='Уровень занятости, в %')),
                ('percent_unemployed', models.FloatField(verbose_name='Уровень безработицы, в %')),
            ],
            options={
                'verbose_name': 'Данные о занятости населения',
                'verbose_name_plural': 'Данные о занятости населения',
            },
        ),
    ]
