# Generated by Django 6.0.2 on 2026-03-05 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_employmentrussia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид экономической деятельности',
                'verbose_name_plural': 'Виды экономической деятельности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentByTypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Численность занятых (тыс. человек)')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_values', to='map.economicactivitytype', verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Занятость по годам',
                'verbose_name_plural': 'Занятость по годам',
                'ordering': ['activity_type', 'year'],
                'indexes': [models.Index(fields=['activity_type', 'year'], name='map_employm_activit_bafdf2_idx')],
                'unique_together': {('activity_type', 'year')},
            },
        ),
    ]
