# Generated by Django 6.0.2 on 2026-03-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_economicactivitytype_employmentbytypeofwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsByTypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('created', models.FloatField(help_text='Количество созданных рабочих мест', verbose_name='Создано рабочих мест (тыс.)')),
                ('liquidated', models.FloatField(help_text='Количество ликвидированных рабочих мест', verbose_name='Ликвидировано рабочих мест (тыс.)')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_values', to='map.economicactivitytype', verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Данные о рабочих местах по годам',
                'verbose_name_plural': 'Данные о рабочих местах по годам',
                'ordering': ['activity_type', 'year'],
                'indexes': [models.Index(fields=['activity_type', 'year'], name='map_jobsbyt_activit_7e8612_idx')],
                'unique_together': {('activity_type', 'year')},
            },
        ),
    ]
