# Generated by Django 6.0.2 on 2026-03-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_jobsbytypeofwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGraduatesHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('all_people', models.FloatField(help_text='Общая численность выпускников', verbose_name='Общая численность выпускников (человек)')),
                ('working', models.FloatField(help_text='Число занятых выпускников', verbose_name='Занятые (человек)')),
                ('not_working', models.FloatField(help_text='Число безработных выпускников', verbose_name='Безработные (человек)')),
                ('can_not_work', models.FloatField(help_text='Число выпускников, не входящих в состав рабочей силы', verbose_name='Не входящие в рабочую силу (человек)')),
                ('employment_percent', models.FloatField(help_text='Доля занятых среди рабочей силы', verbose_name='Уровень занятости (%)')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_grad_he_values', to='map.economicactivitytype', verbose_name='Вид отрасли')),
            ],
            options={
                'verbose_name': 'Занятость выпускников. Высшее образование',
                'verbose_name_plural': 'Занятость выпускников. Высшее образование',
                'ordering': ['-year', 'activity_type'],
                'unique_together': {('activity_type', 'year')},
            },
        ),
    ]
