# Generated by Django 6.0.2 on 2026-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_workinggraduateshe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentrussia',
            name='employ_people',
            field=models.FloatField(blank=True, null=True, verbose_name='Занятые'),
        ),
        migrations.AlterField(
            model_name='employmentrussia',
            name='labor_force',
            field=models.FloatField(blank=True, null=True, verbose_name='Рабочая сила'),
        ),
        migrations.AlterField(
            model_name='employmentrussia',
            name='percent_employed',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень занятости, в %'),
        ),
        migrations.AlterField(
            model_name='employmentrussia',
            name='percent_in_labor',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень участия в составе рабочей силы, в %'),
        ),
        migrations.AlterField(
            model_name='employmentrussia',
            name='percent_unemployed',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень безработицы, в %'),
        ),
        migrations.AlterField(
            model_name='employmentrussia',
            name='unemployed_people',
            field=models.FloatField(blank=True, null=True, verbose_name='Безработные'),
        ),
        migrations.AlterField(
            model_name='jobsbytypeofwork',
            name='created',
            field=models.FloatField(blank=True, help_text='Количество созданных рабочих мест', null=True, verbose_name='Создано рабочих мест (тыс.)'),
        ),
        migrations.AlterField(
            model_name='jobsbytypeofwork',
            name='liquidated',
            field=models.FloatField(blank=True, help_text='Количество ликвидированных рабочих мест', null=True, verbose_name='Ликвидировано рабочих мест (тыс.)'),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='rural_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент сельского населения'),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='rural_population',
            field=models.FloatField(blank=True, null=True, verbose_name='Сельское население'),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='urban_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент городского населения'),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='urban_population',
            field=models.FloatField(blank=True, null=True, verbose_name='Городское население'),
        ),
        migrations.AlterField(
            model_name='workinggraduateshe',
            name='all_people',
            field=models.FloatField(blank=True, help_text='Общая численность выпускников', null=True, verbose_name='Общая численность выпускников (человек)'),
        ),
        migrations.AlterField(
            model_name='workinggraduateshe',
            name='can_not_work',
            field=models.FloatField(blank=True, help_text='Число выпускников, не входящих в состав рабочей силы', null=True, verbose_name='Не входящие в рабочую силу (человек)'),
        ),
        migrations.AlterField(
            model_name='workinggraduateshe',
            name='employment_percent',
            field=models.FloatField(blank=True, help_text='Доля занятых среди рабочей силы', null=True, verbose_name='Уровень занятости (%)'),
        ),
        migrations.AlterField(
            model_name='workinggraduateshe',
            name='not_working',
            field=models.FloatField(blank=True, help_text='Число безработных выпускников', null=True, verbose_name='Безработные (человек)'),
        ),
        migrations.AlterField(
            model_name='workinggraduateshe',
            name='working',
            field=models.FloatField(blank=True, help_text='Число занятых выпускников', null=True, verbose_name='Занятые (человек)'),
        ),
    ]
