# Generated by Django 6.0.2 on 2026-03-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_employmentrussia_employ_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGraduatesSPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('all_people', models.FloatField(blank=True, help_text='Общая численность выпускников', null=True, verbose_name='Общая численность выпускников (человек)')),
                ('working', models.FloatField(blank=True, help_text='Число занятых выпускников', null=True, verbose_name='Занятые (человек)')),
                ('not_working', models.FloatField(blank=True, help_text='Число безработных выпускников', null=True, verbose_name='Безработные (человек)')),
                ('can_not_work', models.FloatField(blank=True, help_text='Число выпускников, не входящих в состав рабочей силы', null=True, verbose_name='Не входящие в рабочую силу (человек)')),
                ('employment_percent', models.FloatField(blank=True, help_text='Доля занятых среди рабочей силы', null=True, verbose_name='Уровень занятости (%)')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_grad_spo_values', to='map.economicactivitytype', verbose_name='Вид отрасли')),
            ],
            options={
                'verbose_name': 'Занятость выпускников. Среднее профессиональное образование',
                'verbose_name_plural': 'Занятость выпускников. Среднее профессиональное образование',
                'ordering': ['-year', 'activity_type'],
                'unique_together': {('activity_type', 'year')},
            },
        ),
    ]
