# Generated by Django 6.0.2 on 2026-03-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_workinggraduatesspo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkInSpecialityHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('all_people', models.FloatField(blank=True, help_text='Общая численность выпускников (тыс. человек)', null=True, verbose_name='Общая численность выпускников ')),
                ('works_by_profession', models.FloatField(blank=True, help_text='Число выпускников, работающих по специальности (тыс. человек)', null=True, verbose_name='Работающие по специальности')),
                ('works_not_by_profession', models.FloatField(blank=True, help_text='Число выпускников, работающих не по специальности (тыс. человек)', null=True, verbose_name='Работающие не по специальности')),
                ('works_by_profession_percent', models.FloatField(blank=True, help_text='Число выпускников, работающих по специальности, %', null=True, verbose_name='Доля работающих по специальности')),
                ('works_not_by_profession_percent', models.FloatField(blank=True, help_text='Число выпускников, работающих не по специальности, %', null=True, verbose_name='Доля не работающих по специальности')),
                ('special_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_he_values', to='map.specialtytype', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Данные о выпускниках, работающих по специальности за 2024 год. Высшее образование',
                'verbose_name_plural': 'Данные о выпускниках, работающих по специальности за 2024 год. Высшее образование',
                'ordering': ['-year', 'special_type'],
                'unique_together': {('special_type', 'year')},
            },
        ),
    ]
