# Generated by Django 6.0.2 on 2026-03-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_specialtytype_workinspecialityhe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinspecialityhe',
            options={'ordering': ['-year', 'special_type'], 'verbose_name': 'Данные о выпускниках, работающих по специальности. Высшее образование', 'verbose_name_plural': 'Данные о выпускниках, работающих по специальности. Высшее образование'},
        ),
    ]
