# Generated by Django 6.0.2 on 2026-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_workinspecialityspo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinggraduatesspo',
            name='all_people',
            field=models.FloatField(blank=True, help_text='Общая численность выпускников', null=True, verbose_name='Общая численность выпускников (тыс.чел.)'),
        ),
        migrations.AlterField(
            model_name='workinggraduatesspo',
            name='can_not_work',
            field=models.FloatField(blank=True, help_text='Число выпускников, не входящих в состав рабочей силы', null=True, verbose_name='Не входящие в рабочую силу (тыс.чел.)'),
        ),
        migrations.AlterField(
            model_name='workinggraduatesspo',
            name='not_working',
            field=models.FloatField(blank=True, help_text='Число безработных выпускников', null=True, verbose_name='Безработные (тыс.чел.)'),
        ),
        migrations.AlterField(
            model_name='workinggraduatesspo',
            name='working',
            field=models.FloatField(blank=True, help_text='Число занятых выпускников', null=True, verbose_name='Занятые (тыс.чел.)'),
        ),
    ]
