# Generated by Django 6.0.2 on 2026-03-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionsRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название региона')),
                ('code', models.SmallIntegerField(max_length=10, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborForceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='год')),
                ('value', models.FloatField(verbose_name='Численность рабочей силы')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_force', to='regions.regionsrf', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Численность рабочей силы по субъектам Российской Федерации',
                'verbose_name_plural': 'Численность рабочей силы по субъектам Российской Федерации',
            },
        ),
    ]
