# Generated by Django 6.0.2 on 2026-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionsrf',
            name='code',
            field=models.SmallIntegerField(verbose_name='Код региона'),
        ),
    ]
