# Generated by Django 6.0.2 on 2026-03-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_regionsrf_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborforceregion',
            name='value',
            field=models.FloatField(verbose_name='Численность рабочей силы (тыс.чел.)'),
        ),
        migrations.AlterField(
            model_name='regionsrf',
            name='code',
            field=models.SmallIntegerField(help_text='Код ОКАТО региона', verbose_name='Код региона'),
        ),
        migrations.CreateModel(
            name='PopulationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='год')),
                ('value', models.FloatField(help_text='Численность населения', verbose_name='Численность населения (тыс.чел.)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='regions.regionsrf', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Численность населения по субъектам Российской Федерации',
                'verbose_name_plural': 'Численность населения по субъектам Российской Федерации',
            },
        ),
    ]
