# Generated by Django 6.0.2 on 2026-03-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_laborforceregion_value_alter_regionsrf_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkForceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='год')),
                ('value', models.FloatField(help_text='участия в рабочей силе по регионам РФ', verbose_name='участия в рабочей силе по регионам РФ (%)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforcelevel', to='regions.regionsrf', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Уровень участия в рабочей силе по регионам РФ',
                'verbose_name_plural': 'участия в рабочей силе по регионам РФ',
            },
        ),
    ]
