# Generated by Django 6.0.2 on 2026-03-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_workforcelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workforcelevel',
            options={'verbose_name': 'Уровень участия в рабочей силе по регионам РФ', 'verbose_name_plural': 'Уровень участия в рабочей силе по регионам РФ'},
        ),
        migrations.AlterField(
            model_name='workforcelevel',
            name='value',
            field=models.FloatField(help_text='Уровень участия в рабочей силе по регионам РФ', verbose_name='Уровень участия в рабочей силе по регионам РФ (%)'),
        ),
        migrations.CreateModel(
            name='WorkForceHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='год')),
                ('value', models.FloatField(help_text='Доля работников с высшим образованием по регионам РФ', verbose_name='Доля работников с высшим образованием по регионам РФ (%)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_he', to='regions.regionsrf', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Доля работников с высшим образованием по регионам РФ',
                'verbose_name_plural': 'Доля работников с высшим образованием по регионам РФ',
            },
        ),
    ]
